language: cpp
dist: bionic
sudo: required
os:
    - linux
    - osx

compiler:
    - gcc
    - clang

script:
    - git submodule update --init --recursive
    - cmake -S. -BBuild
    - cmake --build Build
